# Generated by Django 2.2.4 on 2019-08-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='deleted_by',
        ),
    ]
