# Generated by Django 2.2.4 on 2019-08-08 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20190808_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imagefile',
            field=models.FileField(null=True, upload_to='movies_pictures/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='UserMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movie', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
